DROP TABLE DOCHI.JOB_MST;

CREATE TABLE DOCHI.JOB_MST (
	JOB_ID						VARCHAR(15)		,	
	JOB_TYPE					INT				NOT NULL,
	JOB_NAME					VARCHAR(50)		,
	EXEC_YN						CHAR(1)			DEFAULT 'Y',
	EXEC_SCH_TYPE				INT				NOT NULL,
	EXEC_SCH					VARCHAR(30)		,	-- 0: Fixed, 1: Crontab
	EXEC_SRC					VARCHAR(100)	,	
	REG_USER					VARCHAR(50)		,	
	REG_DTTM					VARCHAR(14)		,	
	UPD_USER					VARCHAR(50)		,	
	UPD_DTTM					VARCHAR(14)
);

ALTER TABLE DOCHI.JOB_MST
	ADD CONSTRAINT PK_JOB_MST
	PRIMARY KEY ( JOB_ID )
;

INSERT INTO DOCHI.JOB_MST (
	JOB_ID
	, JOB_TYPE
	, JOB_NAME
	, EXEC_YN
	, EXEC_SCH_TYPE
	, EXEC_SCH
	, EXEC_SRC
	, REG_USER
	, REG_DTTM
) VALUES (
	CONCAT('JOB', DATE_FORMAT(now(), '%Y%m%d'), '0001')
	, 0		/* 일회성 */
	, 'TEST JOB'
	, 'Y'
	, 1		/* cron */
	, '* 0/15 * * * ?'
	, 'SampleJob'
	, 'ADMIN'
	, DATE_FORMAT(now(), '%Y%m%d%H%i%s')
)
;

SELECT *
  FROM DOCHI.JOB_MST
;



DROP TABLE DOCHI.JOB_SCHEDULE;

CREATE TABLE DOCHI.JOB_SCHEDULE (								
	SCH_ID						VARCHAR(15)		,
	SCH_TYPE					INT				,
	NEXT_SCH_DTATE				VARCHAR(8)		,
	NEXT_SCH_TIME				VARCHAR(6)		,
	RUN_FLAG					CHAR(1)			DEFAULT 'N',
	REG_USER					VARCHAR(50)		,	
	REG_DTTM					VARCHAR(14)		,	
	UPD_USER					VARCHAR(50)		,	
	UPD_DTTM					VARCHAR(14) 	
);

ALTER TABLE DOCHI.JOB_SCHEDULE 
	ADD CONSTRAINT PK_JOB_SCHEDULE
	PRIMARY KEY ( SCH_ID )
;

						

CREATE TABLE DOCHI.JOB_SCH_MAPP (	
JOB_ID					VARCHAR(15)		,					
SCH_ID					VARCHAR(15)		,
REG_USER					VARCHAR(50)		,	
REG_DTTM					VARCHAR(14)		,	
UPD_USER					VARCHAR(50)		,	
UPD_DTTM					VARCHAR(14) 		
);

ALTER TABLE DOCHI.JOB_SCH_MAPP 
	ADD CONSTRAINT PK_JOB_SCH_MAPP
	PRIMARY KEY ( JOB_ID, SCH_ID )
;

